[package]
name = "roast"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
license = "Apache-2.0"

[dependencies]
roast_derives = { version = "0.1", path = "../roast_derives" }
jni = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
