[package]
name = "roast_testlab"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
build = "build.rs"
license = "Apache-2.0"

[dependencies]
roast = { path = "../roast" }

[build-dependencies]
roast = { path = "../roast" }

[lib]
crate_type = ["cdylib"]
